### ISSUE TITLE
Rendering doesn't work. Window goes block 

### ISSUE THREAD

**Issue by abhishek2197** [pat-coady/trpo#11]
Hi!
Our model is training properly and we are getting appropriate results. But the simulation window goes black. mujoco_py version 0.5, mujocopro131.Tried on both ubuntu 16.04 and arch with gnome.

**Comment by pat-coady** [comment]
Hmmm, I'm running same setup and am not having any problems. No one else has mentioned this problem either. Do the video files get saved? They should be /tmp directory.

Have you tried building just a simple, few line notebook. Just load an environment and feed 0s for the action. Just to confirm your setup?

Pat

**Comment by erwincoumans** [comment]
The blank window seems fine, the videos end up in the /tmp folder. Since your training likely calls the Gym 'render' API using the mode="rgb_array" instead of mode="human".

After finishing the training, is there any way to 'enjoy' an existing checkpoint or log file using render="human"?

There is no mention about videos being created and saved in the tmp folder, can you add it to the README, or do you want me to create a PR for that?

**Comment by pat-coady** [comment]
Thanks for debugging. PR would be great.

**Comment by pat-coady** [comment]
Note added to README that videos are created and stored in /tmp folder.
