### ISSUE TITLE
enjoy a pre-trained model after training is done?

### ISSUE THREAD

**Issue by erwincoumans** [pat-coady/trpo#12]
Is there a way to enjoy the pre-trained model (weights/checkpoint) after the training is completed?

Usually (TF Agents, OpenAI Baselines, ES Tool etc) there is a 'train' script that saves the weights of the neural network, and a 'enjoy' script that reads those weights and allows to run the pretrained network.

If it is not available, do you have any hints how it can be added?

**Comment by pat-coady** [comment]
Erwin,

It's relatively straightforward to add a provision to save, load and run a
model. It is slightly more involved than usual here since there are 2 NNs
(value function, policy) and also the scaler coefficients.

Normally I'd volunteer to make the improvement, but I am swamped with other
projects at this time. I'd really like to do an implementation of AlphaGo
Zero.

tensorflow has a saver object, which makes saving and loading weights
fairly easy. I guess the scaler coefficients would need to be saved in a
little text file. Numpy has a handy save, restore method.

Pat

**Comment by llecam** [comment]
Hi,
@erwincoumans I would be interested in writing an "enjoy" script as well. Did you manage to do it since you posted this message ?

Thanks!

Léa

**Comment by erwincoumans** [comment]
I haven't looked into it further. The TensorFlow inspect_checkpoint utility can extract weights from a checkpoint:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py
Please report back if you make progress.

**Comment by pat-coady** [comment]
I've added a note to the README that videos are saved to /tmp as training progresses.

I agree it would be nice to save checkpoints so that training can continue or agents can be viewed. Unfortunately, any free time I find will probably be spent on a new project.
